[package]
name = "fetch-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sismos = { path = "../sismos"}
tokio = { version = "1.25", features = ["macros"]  }
