app = "sismos"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
# required because we can't infer your binary's name
cmd = "./sismos"

[env]
DATABASE_URL = "sqlite://sismos.db"
PORT = 1972
HOST = "0.0.0.0"

[[services]]
internal_port = 1972
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
port = "1972"
restart_limit = 6
timeout = "2s"
